name: pui_part1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^2.0.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.10.0
  firebase_auth_web: ^5.8.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
