// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa28hPtPdgVobL_YIqBoQsn4bQG0evKlg',
    appId: '1:969125227852:web:9853cd81a10691841a73e9',
    messagingSenderId: '969125227852',
    projectId: 'pui1-b3d37',
    authDomain: 'pui1-b3d37.firebaseapp.com',
    databaseURL: 'https://pui1-b3d37-default-rtdb.firebaseio.com',
    storageBucket: 'pui1-b3d37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCTGsoP8ZwqDDeF4hj_RlFOcanz84zlM',
    appId: '1:969125227852:android:0c4cdb8dccd716971a73e9',
    messagingSenderId: '969125227852',
    projectId: 'pui1-b3d37',
    databaseURL: 'https://pui1-b3d37-default-rtdb.firebaseio.com',
    storageBucket: 'pui1-b3d37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6oQMFSTv4o9LsBQHYgQDnpoEi5UBVEg',
    appId: '1:969125227852:ios:a858ecc06b108dac1a73e9',
    messagingSenderId: '969125227852',
    projectId: 'pui1-b3d37',
    databaseURL: 'https://pui1-b3d37-default-rtdb.firebaseio.com',
    storageBucket: 'pui1-b3d37.firebasestorage.app',
    iosBundleId: 'com.example.puiPart1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo6oQMFSTv4o9LsBQHYgQDnpoEi5UBVEg',
    appId: '1:969125227852:ios:a858ecc06b108dac1a73e9',
    messagingSenderId: '969125227852',
    projectId: 'pui1-b3d37',
    databaseURL: 'https://pui1-b3d37-default-rtdb.firebaseio.com',
    storageBucket: 'pui1-b3d37.firebasestorage.app',
    iosBundleId: 'com.example.puiPart1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa28hPtPdgVobL_YIqBoQsn4bQG0evKlg',
    appId: '1:969125227852:web:532ddd534a91b8cf1a73e9',
    messagingSenderId: '969125227852',
    projectId: 'pui1-b3d37',
    authDomain: 'pui1-b3d37.firebaseapp.com',
    databaseURL: 'https://pui1-b3d37-default-rtdb.firebaseio.com',
    storageBucket: 'pui1-b3d37.firebasestorage.app',
  );

}